Added radiolink txs to build targets list
DeviationTX/deviation-docker pull request #7
Opened 2019-05-01 19:16 UTC by SilverFire

2019-05-04 19:04 UTC, TheRealMoeder requested changes
the non devo targets just got lost in the scripts build target list due to major code refactoring in the deviation repository. Please add opentx directory as well and I see no reason not to merge this.

2019-05-13 15:09 UTC, SilverFire commented
@TheRealMoeder done

2019-05-13 20:17 UTC, TheRealMoeder approved these changes

2019-05-13 20:17 UTC, TheRealMoeder commented
Thanks!

2019-05-13 20:17 UTC, merged